# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=80)),
                ('condition', models.CharField(choices=[('select', 'SELECT'), ('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], default='select', max_length=20)),
                ('dob', models.DateField()),
                ('AboveEighteen', models.BooleanField()),
            ],
        ),
    ]
