# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='condition',
            new_name='Gender',
        ),
    ]
